name: CI MB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash  
    
jobs:
  setup:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          if [ $RUNNER_OS == 'Windows' ]; then
            powershell -Command "Invoke-WebRequest -Uri https://install.python-poetry.org -OutFile install-poetry.py"
            powershell -Command "python install-poetry.py"
          else
            curl -sSL https://install.python-poetry.org | python3 -
          fi
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        working-directory: ./example-app
        run: poetry install --no-root

      - name: Cache build venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: ./example-app/.venv
          key: ${{ runner.os }}-venv

  static_tests:
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        test_type: ['lint', 'formatter', 'security']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          if [ $RUNNER_OS == 'Windows' ]; then
            powershell -Command "Invoke-WebRequest -Uri https://install.python-poetry.org -OutFile install-poetry.py"
            powershell -Command "python install-poetry.py"
          else
            curl -sSL https://install.python-poetry.org | python3 -
          fi
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        working-directory: ./example-app
        run: poetry install --no-root

      - name: Run ${{ matrix.test_type }}
        working-directory: ./example-app
        run: poetry run task ${{ matrix.test_type }}

  unit_tests:
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          if [ $RUNNER_OS == 'Windows' ]; then
            powershell -Command "Invoke-WebRequest -Uri https://install.python-poetry.org -OutFile install-poetry.py"
            powershell -Command "python install-poetry.py"
          else
            curl -sSL https://install.python-poetry.org | python3 -
          fi
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        working-directory: ./example-app
        run: poetry install --no-root

      - name: Run Unit Tests
        working-directory: ./example-app
        run: poetry run task test
