name: Deploy Renderu MB

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Render CLI
        run: |
          curl -fsSL https://cdn.render.com/cli.sh | sh
          
      - name: Deploy with Render
        run: |
          render deploy --file render.yaml
