name: Deploy Render MB

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Render CLI
        run: |
          curl -fsSL https://cdn.render.com/cli.sh | sh
          echo "$HOME/.render/bin" >> $GITHUB_PATH 
          
      - name: Deploy with Render
        run: |
          render deploy --file render.yaml
